# Generated by Django 4.2.1 on 2025-03-16 04:08

import django.contrib.auth.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(help_text='Telefon raqam yoki Email', max_length=255, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('image', models.ImageField(blank=True, help_text='Profil rasmi', null=True, upload_to='media/user_image/')),
                ('phone_number', models.CharField(blank=True, help_text='Telefon raqam', max_length=13, null=True, unique=True)),
                ('email', models.EmailField(blank=True, help_text='Ixtiyoriy', max_length=254, null=True)),
                ('role', models.CharField(choices=[('teacher', 'O‘qituvchi'), ('student', 'Talaba')], default='student', max_length=10)),
                ('subject', models.CharField(blank=True, help_text='O‘qituvchi uchun fan yo‘nalishi', max_length=100, null=True)),
                ('region', models.CharField(blank=True, help_text='Talaba uchun viloyat', max_length=100, null=True)),
                ('district', models.CharField(blank=True, help_text='Talaba uchun tuman', max_length=100, null=True)),
                ('school', models.CharField(blank=True, help_text='Talaba uchun maktab', max_length=100, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Erkak', 'Erkak'), ('Ayol', 'Ayol')], help_text='Talaba uchun jins', max_length=10, null=True)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
