# Generated by Django 4.2.1 on 2025-03-10 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfflineStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Oflayn Student',
                'verbose_name_plural': 'Oflayn Studentlar',
            },
        ),
        migrations.AlterModelOptions(
            name='class',
            options={'verbose_name': 'Sinf', 'verbose_name_plural': 'Sinflar'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'verbose_name': 'Fan', 'verbose_name_plural': 'Fanlar'},
        ),
    ]
